networks:
  app:
    driver: bridge
    external: true

services:
  calendarservice_db:
    image: postgres:latest
    container_name: calendarservice_db
    env_file: /src/.env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-calendarservice_db}
      - PGPORT=5435
    networks:
      app:
    ports:
      - "5435:5435"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10

#  calendarservice_back:
#    image: couldl1e/calendarservice_back:latest
#    container_name: calendarservice_back
#    build:
#      context: ./
#    networks:
#      app:
#    depends_on:
#      calendarservice_db:
#        condition: service_healthy
#    ports:
#      - "8078:8078"

