
networks:
  authservice_app:

services:
#  authservice_back:
#    image: ignaxa/authservice_back:latest
#    container_name: authservice_back
#    build:
#      context: ./authservice-backend
#    networks:
#      authservice_app:
#    ports:
#      - "8080:8080"

  authservice_db:
    image: postgres:latest
    container_name: authservice_db
    env_file: authservice-backend/src/.env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-authservice_db}
    networks:
      authservice_app:
    ports:
      - "5432:5432"
