
networks:
  authservice_app:

services:
  authservice_db:
    image: postgres:latest
    container_name: authservice_db
    env_file: authservice-backend/src/.env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-authservice_db}
    networks:
      authservice_app:
    ports:
      - "5432:5432"

  authservice_back:
    image: ignaxa/authservice_back:latest
    container_name: authservice_back
    build:
      context: ./authservice-backend
    networks:
      authservice_app:
    depends_on:
      - authservice_db
    ports:
      - "8080:8080"

    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s