
networks:
  authservice_app:
    driver: bridge

services:
  authservice_db:
    image: postgres:latest
    container_name: authservice_db
    env_file: /src/.env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-authservice_db}
    networks:
      authservice_app:

  authservice_back:
    image: ignaxa/authservice_back:latest
    container_name: authservice_back
    build:
      context: ./
    networks:
      authservice_app:
    depends_on:
      - authservice_db
    ports:
      - "8080:8080"

    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s