networks:
  profileservice_app:
    driver: bridge

services:
  profileservice_db:
    image: postgres:latest
    container_name: profileservice_db
    env_file: /src/.env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-profileservice_db}
      - PGPORT=5434
    networks:
      profileservice_app:
    ports:
      - "5434:5434"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10

#  profileservice_back:
#    image: couldl1e/profileservice_back:latest
#    container_name: profileservice_back
#    build:
#      context: ./
#    networks:
#      profileservice_app:
#    depends_on:
#      profileservice_db:
#        condition: service_healthy
#    ports:
#      - "8079:8079"


