
networks:
  authservice_app:
    driver: bridge

services:
  authservice_db:
    image: postgres:latest
    container_name: authservice_db
    env_file: /src/.env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-authservice_db}
      - PGPORT=5433
    networks:
      authservice_app:
    ports:
      - "5433:5433"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10


#  authservice_back:
#    image: ignaxa/authservice_back:latest
#    container_name: authservice_back
#    build:
#      context: ./
#    networks:
#      authservice_app:
#    depends_on:
#      authservice_db:
#        condition: service_healthy
#    ports:
#      - "8081:8081"